import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import {
  Shield, Users, Trophy, Loader2, Plus, Search,
  Crown, Lock, Unlock, ArrowRight, Calendar, Briefcase
} from 'lucide-react';

const MyTeams = () => {
  const navigate = useNavigate();
  const apiUrl = process.env.REACT_APP_API_URL;
  const [teams, setTeams] = useState([]);
  const [loading, setLoading] = useState(true);
  const [searchQuery, setSearchQuery] = useState('');

  useEffect(() => {
    const fetchMyTeams = async () => {
      try {
        const token = localStorage.getItem('token');
        const res = await fetch(`${apiUrl}/api/teams/my/teams`, {
          headers: { Authorization: `Bearer ${token}` }
        });
        if (res.ok) setTeams(await res.json());
      } catch (err) {
        console.error('Помилка завантаження команд:', err);
      } finally {
        setLoading(false);
      }
    };
    fetchMyTeams();
  }, [apiUrl]);

  const filteredTeams = teams.filter(team =>
    team.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
    team.hackathon?.title?.toLowerCase().includes(searchQuery.toLowerCase())
  );

  const getHackathonStatus = (start, end) => {
    const now = new Date();
    if (now < new Date(start)) return { label: 'Скоро', color: 'text-blue-400' };
    if (now <= new Date(end)) return { label: 'Активний', color: 'text-emerald-400' };
    return { label: 'Завершено', color: 'text-slate-500' };
  };

  if (loading) return (
    <div className="flex justify-center items-center min-h-screen bg-[#020617]">
      <Loader2 className="animate-spin text-indigo-500" size={40} />
    </div>
  );

  return (
    <div className="min-h-screen bg-[#020617] text-slate-200 pb-20 pt-8">
      <div className="max-w-5xl mx-auto px-4 sm:px-6">

        {/* Хедер */}
        <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 mb-8">
          <div>
            <h1 className="text-3xl font-bold text-white flex items-center gap-3">
              <Shield className="text-indigo-400" size={32} /> Мої команди
            </h1>
            <p className="text-slate-400 mt-1">Всі команди в яких ти берешь участь</p>
          </div>
          <button
            onClick={() => navigate('/hackathons')}
            className="flex items-center gap-2 px-5 py-2.5 bg-indigo-600 hover:bg-indigo-500 text-white font-semibold rounded-xl transition-all"
          >
            <Plus size={18} /> Знайти хакатон
          </button>
        </div>

        {/* Пошук */}
        <div className="relative mb-8">
          <Search className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-500" size={18} />
          <input
            type="text"
            placeholder="Пошук за назвою команди або хакатону..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            className="w-full bg-slate-900 border border-slate-800 rounded-xl pl-11 pr-4 py-3 text-white placeholder-slate-500 focus:outline-none focus:border-indigo-500 transition-colors"
          />
        </div>

        {/* Список команд */}
        {filteredTeams.length > 0 ? (
          <div className="space-y-4">
            {filteredTeams.map((team) => {
              const hackStatus = team.hackathon
                ? getHackathonStatus(team.hackathon.startDate, team.hackathon.endDate)
                : null;
              const isLocked = team.lockedAt && new Date() >= new Date(team.lockedAt);

              return (
                <div
                  key={team._id}
                  className="bg-gradient-to-br from-slate-800/60 via-slate-800/40 to-indigo-950/40 border border-slate-700/50 hover:border-indigo-500/30 rounded-2xl p-6 transition-all"
                >
                  <div className="flex flex-col sm:flex-row gap-4 items-start sm:items-center justify-between">
                    <div className="flex-1 min-w-0">

                      {/* Назва і бейджі */}
                      <div className="flex flex-wrap items-center gap-2 mb-2">
                        <h3 className="text-lg font-bold text-white">{team.name}</h3>

                        {team.isCaptain && (
                          <span className="flex items-center gap-1 text-[10px] bg-amber-500/10 text-amber-400 border border-amber-500/20 px-2 py-0.5 rounded-full font-bold">
                            <Crown size={9} /> Капітан
                          </span>
                        )}
                        {team.isAutoGenerated && (
                          <span className="text-[10px] bg-slate-700 text-slate-400 px-2 py-0.5 rounded-full">Авто</span>
                        )}
                        {isLocked ? (
                          <span className="flex items-center gap-1 text-[10px] bg-rose-500/10 text-rose-400 border border-rose-500/20 px-2 py-0.5 rounded-full">
                            <Lock size={9} /> Заблокована
                          </span>
                        ) : team.isOpen ? (
                          <span className="flex items-center gap-1 text-[10px] bg-emerald-500/10 text-emerald-400 border border-emerald-500/20 px-2 py-0.5 rounded-full">
                            <Unlock size={9} /> Відкрита
                          </span>
                        ) : (
                          <span className="text-[10px] bg-slate-800 text-slate-500 border border-slate-700 px-2 py-0.5 rounded-full">Закрита</span>
                        )}
                      </div>

                      {/* Хакатон */}
                      {team.hackathon && (
                        <div className="flex items-center gap-2 text-sm text-slate-400 mb-3">
                          <Trophy size={14} className="text-amber-400 shrink-0" />
                          <span className="truncate">{team.hackathon.title}</span>
                          {hackStatus && (
                            <span className={`text-xs font-medium shrink-0 ${hackStatus.color}`}>
                              · {hackStatus.label}
                            </span>
                          )}
                        </div>
                      )}

                      {/* Опис */}
                      {team.description && (
                        <p className="text-sm text-slate-400 mb-3 line-clamp-1">{team.description}</p>
                      )}

                      {/* Метрики */}
                      <div className="flex flex-wrap gap-4 text-xs text-slate-500">
                        <span className="flex items-center gap-1.5">
                          <Users size={12} /> {team.membersCount} учасників
                        </span>
                        {team.primaryRole && (
                          <span className="flex items-center gap-1.5">
                            <Briefcase size={12} /> Моя роль: {team.primaryRole}
                          </span>
                        )}
                        {team.hackathon?.startDate && (
                          <span className="flex items-center gap-1.5">
                            <Calendar size={12} /> {new Date(team.hackathon.startDate).toLocaleDateString('uk-UA')}
                          </span>
                        )}
                        {/* Нові заявки для капітана */}
                        {team.isCaptain && team.pendingApplications > 0 && (
                          <span className="flex items-center gap-1.5 text-indigo-400 font-medium">
                            <span className="w-2 h-2 rounded-full bg-indigo-400 animate-pulse" />
                            {team.pendingApplications} нових заявок
                          </span>
                        )}
                      </div>

                      {/* Кого шукають */}
                      {team.lookingFor?.length > 0 && team.isOpen && !isLocked && (
                        <div className="flex flex-wrap gap-1.5 mt-3 items-center">
                          <span className="text-[10px] text-slate-500">Шукають:</span>
                          {team.lookingFor.map((role, i) => (
                            <span key={i} className="text-[10px] px-2 py-0.5 bg-slate-800 border border-slate-700 text-slate-400 rounded-md">
                              {role}
                            </span>
                          ))}
                        </div>
                      )}
                    </div>

                    {/* Кнопки */}
                    <div className="flex flex-col gap-2 shrink-0 w-full sm:w-auto">
                      <button
                        onClick={() => navigate(`/hackathons/${team.hackathon?._id}/teams/${team._id}`)}
                        className="flex items-center justify-center gap-2 px-5 py-2.5 bg-indigo-600 hover:bg-indigo-500 text-white font-semibold rounded-xl transition-all text-sm"
                      >
                        Кабінет команди <ArrowRight size={16} />
                      </button>
                      <button
                        onClick={() => navigate(`/hackathons/${team.hackathon?._id}/teams`)}
                        className="flex items-center justify-center gap-2 px-5 py-2 bg-slate-800 hover:bg-slate-700 text-slate-300 rounded-xl transition-all text-sm border border-slate-700"
                      >
                        Всі команди хакатону
                      </button>
                    </div>
                  </div>
                </div>
              );
            })}
          </div>
        ) : (
          <div className="text-center py-20 border-2 border-dashed border-slate-800 rounded-3xl">
            <Shield className="mx-auto text-slate-700 mb-4" size={48} />
            <p className="text-slate-400 text-lg font-medium mb-2">
              {searchQuery ? 'Нічого не знайдено' : 'Ти ще не в жодній команді'}
            </p>
            <p className="text-slate-600 text-sm mb-6">
              {searchQuery
                ? 'Спробуй змінити параметри пошуку'
                : 'Знайди хакатон і приєднайся до команди або створи власну'
              }
            </p>
            {!searchQuery && (
              <button
                onClick={() => navigate('/hackathons')}
                className="px-6 py-2.5 bg-indigo-600 hover:bg-indigo-500 text-white rounded-xl font-medium transition-colors"
              >
                Знайти хакатон
              </button>
            )}
          </div>
        )}
      </div>
    </div>
  );
};

export default MyTeams;